"""Add currency to accounts

Revision ID: 5efb3229e8f4
Revises: 712c08307c56
Create Date: 2026-07-17 01:42:21.172124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5efb3229e8f4'
down_revision: Union[str, Sequence[str], None] = '712c08307c56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('name', sa.String(length=100), nullable=False))
    op.drop_column('accounts', 'holder_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('holder_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('accounts', 'name')
    # ### end Alembic commands ###
